### ISSUE TITLE
一些笔误

### ISSUE THREAD

**Issue by HairlessVillager** [langyo/this-is-the-c-s-world#3]
https://langyo-v2.gitbook.io/cppworld/di-yi-dan-di-san-zhang-ji-suan-shu/3-3

> 运行时的输出是这样的：
>>234 233
>>234 233
>
>前一个`n`似乎合情合理，输出的是加过一后的值，但后一个`m`却还没加就把数字打出来了。不过，从第二行`cout`的输出结果可以看出，它们都自己加了一，工作的挺正常。

此处的输出结果有误，应为
>234 233
>234 234

望及时更正qwq

**Comment by HairlessVillager** [comment]
还有还有，
>我们可以从中看出，如果递增(减)运算符是写在某变量之前的(称作前置运算符或后缀运算符)，那么递增(减)将立即执行，你所收集到的值也会是加(减)过后的样子；

应为：
>我们可以从中看出，如果递增(减)运算符是写在某变量之前的(称作前置运算符或前缀运算符)，那么递增(减)将立即执行，你所收集到的值也会是加(减)过后的样子；

**Comment by langyo** [comment]
很抱歉,我到现在才看到..

稍后更改
